args:
  logdir: /home/fedor_chervinskii/learning-to-move-starter-kit/logs/logs/190905-0712-ddpg

db:
  port: 12000
  prefix: ddpg  # TODO: remove

agents:
  actor:
    agent: SkeletonActor
    policy_head_params:  # hidden representation -> ~policy
      policy_type: null
      out_activation: Tanh

algorithm:
  algorithm: DDPG
